name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Compile encoder
        uses: ./.github/actions/build
      - name: Upload
        if: github.ref == 'refs/heads/prod'
        uses: actions/upload-artifact@v2
        with:
          path: |
            *.js
            *.css
            *.html
            README.md
            LICENSE
            media/**
            encoder/*.js
            encoder/*.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Download
        uses: actions/download-artifact@v2
      - name: Publish
        run: |
          git config --global user.name 'João Moreno'
          git config --global user.email 'joaomoreno@users.noreply.github.com'
          git add .
          # git commit -m 'update encoder'
          # git push
