name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Compile encoder
        uses: ./.github/actions/build
      - name: Upload encoder
        uses: actions/upload-artifact@v2
        with:
          name: encoder
          path: |
            encoder/encoder.js
            encoder/encoder.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Download encoder
        uses: actions/download-artifact@v2
        with:
          name: encoder
          path: encoder
      - name: Publish
        run: |
          git config --global user.name 'João Moreno'
          git config --global user.email 'joaomoreno@users.noreply.github.com'
          git add encoder/encoder.{js,wasm}
          git commit -m 'update encoder'
          git push
